improving script 'count', we've implemented functions, specially presenting proper 'usage' message and so on

diff --git a/pluralsight/count b/pluralsight/count
--- a/pluralsight/count
+++ b/pluralsight/count
@@ -1,42 +1,66 @@
 #!/bin/bash
 
 # this script prints a range of numbers
-# usage: count [-r] [-b n] [-s n] stop
-# -b gives the number to begin with (default: 0)
-# -r reverse the count
-# -s sets step size (default: 1)
-# counting will stop at stop
+
+usage() {
+	cat <<END
+count [-r] [-b n] [-s n] stop
+
+Print each number up to stop, begining at 0
+	-h: show this help message
+	-b: number to begin with (default: 0)
+	-r: reverse the count
+	-s: sets step size (default: 1)
+END
+}
+
+# function to handle errors.
+# first argument: error message to print
+# second argument: exit code to exit script with
+error() {
+	echo "Error: $1"
+	usage
+	exit $2
+} >&2
+
+# function return 0 when it's argument is a number
+isnum() {
+	[[ $1 =~ ^[0-9]+$ ]]
+}
 
 declare reverse=""
 declare -i begin=0
 declare -i step=1
 
-while getopts ":b:s:r" opt; do
+while getopts ":hrb:s:" opt; do
 	case $opt in
 		r)
 			reverse="yes"
 			;;
 		b)
-			[[ ${OPTARG} =~ ^[0-9]+$ ]] || { echo "${OPTARG} is not a number" >&2; exit 1; }
+			isnum ${OPTARG} || error "${OPTARG} is not a number" 1
 			start="${OPTARG}"
 			;;
+		h)
+			usage
+			exit 0
+			;;
 		s)
-			[[ ${OPTARG} =~ ^[0-9]+$ ]] || { echo "${OPTARG} is not a number" >&2; exit 1; }
+			isnum ${OPTARG} || error "${OPTARG} is not a number" 1
 			step="${OPTARG}"
 			;;
 		:)
-			echo "Option -${OPTARG} is missing an argument"
-			exit 1;
+			error "Option -${OPTARG} is missing an argument" 2
 			;;
 		\?)
-			exit 1;
+			error "Unknown option: -${OPTARG}" 3
 			;;
 	esac
 done
 
 shift $(( OPTIND -1 ))
 
-[[ $1 ]] || { echo "missing argument" >&2; exit 1; }
+[[ $1 ]] || error "The 'stop' argument was not provided" 4
 declare end="$1"
 
 if [[ ! $reverse ]]; then
