improving scripts 'create_script' and 'tn' (take notes), also adding 'printargs' and 'count'

diff --git a/pluralsight/tn b/pluralsight/tn
--- a/pluralsight/tn
+++ b/pluralsight/tn
@@ -4,13 +4,29 @@
 # Author: jvillete
 
 # get the date
-date=$(date)
+declare -r date=$(date)
 
 # get topic
-topic="$1"
+declare -r topic="$1"
+
+# determine where to save our notes
+declare notesdir="${HOME}"
+[[ $NOTESDIR ]] && notesdir="${NOTESDIR}"
+
+if [[ ! -d $notesdir ]]; then
+	mkdir "${notesdir}" 2> /dev/null || { echo "Cannot make directory ${notesdir}" 1>&2; exit 1; }
+fi
 
 # filename to write to
-filename="${HOME}/${topic}notes.txt"
+declare -r filename="${notesdir}/${topic}notes.txt"
+
+# does file exits? if not, create it
+if [[ ! -f $filename ]]; then
+	touch "${filename}" 2> /dev/null || { echo "Cannot create file ${filename}" 1>&2; exit 1; }
+fi
+
+# is file writeable?
+[[ -w $filename ]] || { echo "${filename} is not writeable" 1>&2; exit 1; }
 
 # Ask user for input
 read -p "Your note: " note
