updating scripts meanwhile studing topic 'end of options', which is in somehow required when dealing with file/directory on the file system, and the name is provided by the user

diff --git a/pluralsight/tn b/pluralsight/tn
--- a/pluralsight/tn
+++ b/pluralsight/tn
@@ -13,7 +13,7 @@ declare -r topic="$1"
 declare notesdir=${NOTESDIR:-$HOME}
 
 if [[ ! -d $notesdir ]]; then
-	mkdir "${notesdir}" 2> /dev/null || { echo "Cannot make directory ${notesdir}" 1>&2; exit 1; }
+	mkdir -- "${notesdir}" 2> /dev/null || { echo "Cannot make directory ${notesdir}" 1>&2; exit 1; }
 fi
 
 # filename to write to
@@ -21,7 +21,7 @@ declare -r filename="${notesdir}/${topic}notes.txt"
 
 # does file exits? if not, create it
 if [[ ! -f $filename ]]; then
-	touch "${filename}" 2> /dev/null || { echo "Cannot create file ${filename}" 1>&2; exit 1; }
+	touch -- "${filename}" 2> /dev/null || { echo "Cannot create file ${filename}" 1>&2; exit 1; }
 fi
 
 # is file writeable?
